[project]
name = "recod-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "avp-stream>=1.0",
    "grpcio-tools>=1.60.0",  # 修复 Python 3.11 兼容性问题
    "grpcio>=1.60.0",  # 确保 grpcio 版本也兼容
    # local-robot-control
    "numpy>=1.22.4,<2.0.0",
    "opencv-python>=4.11.0.86",
#    "openpi-client",
    "pymodbus==2.5.3",
    "pynput>=1.8.1",
    "pyorbbecsdk",
    "pyrealsense2>=2.56.5.9235",
    "scipy>=1.16.2",
    "typing-extensions>=4.15.0",
    "tyro>=0.9.33",
    "ur-rtde>=1.6.2",
    "cmake>=3.29.0.1",
    "datasets>=2.19.0",
    "deepdiff>=7.0.1",
    "diffusers>=0.27.2",
    "draccus==0.10.0",
    "einops>=0.8.0",
    "flask>=3.0.3",
    "gdown>=5.1.0",
    "gymnasium==0.29.1", # TODO(rcadene, aliberts): Make gym 1.0.0 work
    "h5py>=3.10.0",
    "huggingface-hub[hf-transfer,cli]>=0.27.1 ; python_version < '4.0'",
    "imageio[ffmpeg]>=2.34.0",
    "jsonlines>=4.0.0",
    "numba>=0.59.0",
    "omegaconf>=2.3.0",
    "opencv-python-headless>=4.9.0",
    "packaging>=24.2",
    "av>=14.2.0",
    "pymunk>=6.6.0,<7.0.0",
    "pynput>=1.7.7",
    "pyserial>=3.5",
    "pyzmq>=26.2.1",
    "rerun-sdk>=0.21.0",
    "scipy>=1.14.0",
    "termcolor>=2.4.0",
    "torch>=2.2.1",
    "torchcodec>=0.2.1; sys_platform != 'win32' and (sys_platform != 'linux' or (platform_machine != 'aarch64' and platform_machine != 'arm64' and platform_machine != 'armv7l')) and (sys_platform != 'darwin' or platform_machine != 'x86_64')",
    "torchvision>=0.21.0",
    "wandb>=0.16.3",
    "zarr>=2.17.0",
]

[tool.uv.sources]
pyorbbecsdk = { path = "src/lerobot/robots/ur5e/ur5e_lib/pyorbbecsdk_whl/pyorbbecsdk-2.0.13-cp311-cp311-linux_x86_64.whl" }
